name: Enviable

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - uses: DeLaGuardo/setup-clojure@master
      with:
        cli: '1.10.1.708'
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('enviable/deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Run tests
      run: lein test