name: Enviable

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DEPLOY_USERNAME: johncowie
      DEPLOY_TOKEN: blah

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - uses: DeLaGuardo/setup-clojure@master
      with:
        cli: '1.10.1.708'
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('enviable/deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Run tests
      run: lein test
    - name: Generate Credentials File
      run: mkdir ~/.lein && ./gen-creds.sh $DEPLOY_USERNAME $DEPLOY_TOKEN > ~/.lein/credentials.clj
    - name: Output Credentials
      run: cat ~/.lein/credentials.clj
    - name: Deploy to Clojars
      if: github.ref != 'refs/heads/master'
      run: echo "Fake release"


     #    '{#"https://repo.clojars.org" {:username "milgrim" :password "$ENV"}}'