name: Enviable

on:
  push:
    branches: [ master ]
    tags: ['*']
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DEPLOY_USERNAME: johncowie
      DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - uses: DeLaGuardo/setup-clojure@master
      with:
        cli: '1.10.1.708'
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('enviable/deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Run tests
      run: lein test
    - name: Show Ref
      run: echo "Github ref " ${{ github.ref }}
    - name: Deploy Release
      if: startsWith(github.ref, 'refs/tags')
      run: |
        echo "${GITHUB_REF#refs/*/}" | xargs lein set-version
        cat project.clj
        # lein deploy releases
        lein next-snapshot
        cat project.clj
        # git commit - see https://github.com/marketplace/actions/add-commit


      # TODO Echo tag to a file
      # deploy
      # call `lein set-snapshot` to upgrade snapshot version
      # commit new snapshot version?
    - name: Deploy to Clojars
      if: github.ref == 'refs/heads/master'
      run: lein deploy releases


